[package]
name = "faythe"
version = "0.1.0"
authors = ["Johan Thomsen <jth@dbc.dk>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = "1.0.100"
serde_derive = "1.0.100"
serde_json = "1.0.40"
custom_error = "1.7.1"
x509-parser = "0.6.0"
base64 = "0.10.1"
time = "0.1.42"
trust-dns-resolver = "0.12.0"
openssl = "0.10.25"
acme-lib = "0.5.2"

[dependencies.trust-dns]
version = "0.17"
default-features = false
features = ["dns-over-openssl", "dnssec-openssl"]
